> ### **Assignment 2 - Numpy Array Operations**
>
> This assignment is part of the course ["Data Analysis with Python: Zero to Pandas"](http://zerotopandas.com). The objective of this assignment is to develop a solid understanding of Numpy array operations. In this assignment you will:
>
> 1. Pick 5 interesting Numpy array functions by going through the documentation: https://numpy.org/doc/stable/reference/routines.html
> 2. Run and modify this Jupyter notebook to illustrate their usage (some explanation and 3 examples for each function). Use your imagination to come up with interesting and unique examples.
> 3. Upload this notebook to your Jovian profile using `jovian.commit` and make a submission here: https://jovian.ml/learn/data-analysis-with-python-zero-to-pandas/assignment/assignment-2-numpy-array-operations
> 4. (Optional) Share your notebook online (on Twitter, LinkedIn, Facebook) and on the community forum thread: https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575 .
> 5. (Optional) Check out the notebooks [shared by other participants](https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575) and give feedback & appreciation.
>
> The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.
>
> Try to give your notebook a catchy title & subtitle e.g. "All about Numpy array operations", "5 Numpy functions you didn't know you needed", "A beginner's guide to broadcasting in Numpy", "Interesting ways to create Numpy arrays", "Trigonometic functions in Numpy", "How to use Python for Linear Algebra" etc.
>
> **NOTE**: Remove this block of explanation text before submitting or sharing your notebook online - to make it more presentable.


# Title Here


### Subtitle Here

Write a short introduction about Numpy and list the chosen functions.

- function 1
- function 2
- function 3
- function 4
- function 5

The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.

In [ ]:
!pip install jovian --upgrade -q

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 68.6/68.6 kB 1.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done


In [ ]:
import jovian

In [ ]:
jovian.commit(project='numpy-array-operations')

[jovian] Detected Colab notebook...
[jovian] jovian.commit() is no longer required on Google Colab. If you ran this notebook from Jovian, 
then just save this file in Colab using Ctrl+S/Cmd+S and it will be updated on Jovian. 
Also, you can also delete this cell, it's no longer necessary.


Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [ ]:
import numpy as np

In [ ]:
# List of functions explained
function1 = np.concatenate  # (change this)
# function2 = ???
# function3 = ???
# function4 = ???
# function5 = ???

## Function 1 - np.concatenate (change this)

Add some explanation about the function in your own words

In [ ]:
# Example 1 - working (change this)
arr1 = [[1, 2],
        [3, 4.]]

arr2 = [[5, 6, 7],
        [8, 9, 10]]

np.concatenate((arr1, arr2), axis=1)

array([[ 1.,  2.,  5.,  6.,  7.],
       [ 3.,  4.,  8.,  9., 10.]])

Explanation about example

In [ ]:
# Example 2 - working
arr3 = np.array([4,5,6])
arr4 = np.array([10,9,8])
np.concatenate((arr3,arr4), axis=0)

array([ 4,  5,  6, 10,  9,  8])

Explanation about example

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
arr1 = [[1, 2],
        [3, 4.]]

arr2 = [[5, 6, 7],
        [8, 9, 10]]

np.concatenate((arr1, arr2), axis=0)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 3

Explanation about example (why it breaks and how to fix it)

Some closing comments about when to use this function.

In [ ]:
jovian.commit()

[jovian] Detected Colab notebook...
[jovian] jovian.commit() is no longer required on Google Colab. If you ran this notebook from Jovian, 
then just save this file in Colab using Ctrl+S/Cmd+S and it will be updated on Jovian. 
Also, you can also delete this cell, it's no longer necessary.


## Function 2 - ???

Add some explanations

In [ ]:
# Example 1 - working
arr1 = np.array([1,2,3,4,5])
arr1 + 3

array([4, 5, 6, 7, 8])

Explanation about example

In [ ]:
# Example 2 - working
arr2 = np.array([[1,2,3],
                 [4,5,60],
                 [7,8,9]])
arr2 +5

array([[ 6,  7,  8],
       [ 9, 10, 65],
       [12, 13, 14]])

Explanation about example

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
arr3 = np.array([])
arr3 + 0.5

array([], dtype=float64)

Explanation about example (why it breaks and how to fix it)

Some closing comments about when to use this function.

In [ ]:
jovian.commit()

[jovian] Detected Colab notebook...
[jovian] jovian.commit() is no longer required on Google Colab. If you ran this notebook from Jovian, 
then just save this file in Colab using Ctrl+S/Cmd+S and it will be updated on Jovian. 
Also, you can also delete this cell, it's no longer necessary.


## Function 3 - ???

Add some explanations

In [ ]:
# Example 1 - working
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])
arr1+arr2

array([ 7,  9, 11, 13, 15])

Explanation about example

In [ ]:
# Example 2 - working
arr3 = np.array([[1,2,3],
         [4,5,6]])
arr4 = np.array([[7,8,9],
                 [10,11,12]])
arr3+arr4

array([[ 8, 10, 12],
       [14, 16, 18]])

Explanation about example

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
arr5 = np.array([[1,2,3],
         [4,5,6]])
arr6 = np.array([7,8,9,10])
arr5+arr6

ValueError: operands could not be broadcast together with shapes (2,3) (4,) 

Explanation about example (why it breaks and how to fix it)

Some closing comments about when to use this function.

In [ ]:
jovian.commit()

[jovian] Detected Colab notebook...
[jovian] jovian.commit() is no longer required on Google Colab. If you ran this notebook from Jovian, 
then just save this file in Colab using Ctrl+S/Cmd+S and it will be updated on Jovian. 
Also, you can also delete this cell, it's no longer necessary.


## Function 4 - ???

Add some explanations

In [ ]:
# Example 1 - working
arr1 = np.array([[1, 2, 3], [3, 4, 5]])
arr2 = np.array([[2, 2, 3], [1, 2, 5]])
arr1 == arr2

array([[False,  True,  True],
       [False, False,  True]])

Explanation about example

In [ ]:
# Example 2 - working
arr1 >= arr2

array([[False,  True,  True],
       [ True,  True,  True]])

Explanation about example

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
arr1 = np.array([[1, 2, 3,11], [3, 4, 5,10]])
arr2 = np.array([[2, 2, 3], [1, 2, 5]])
arr1 == arr2

ValueError: operands could not be broadcast together with shapes (2,4) (2,3) 

Explanation about example (why it breaks and how to fix it)

Some closing comments about when to use this function.

In [ ]:
jovian.commit()

[jovian] Detected Colab notebook...
[jovian] jovian.commit() is no longer required on Google Colab. If you ran this notebook from Jovian, 
then just save this file in Colab using Ctrl+S/Cmd+S and it will be updated on Jovian. 
Also, you can also delete this cell, it's no longer necessary.


## Function 5 - ???

Add some explanations

In [ ]:
# Example 1 - working
arr3 = np.array([
    [[1, 2, 3, 4],
     [5, 6, 7, 8]],

    [[15, 16, 17, 21],
     [63, 92, 36, 18]],

    [[98, 32, 81, 23],
     [17, 18, 19.5, 43]]])
arr3.shape
arr3[1, 1, 2]

36.0

Explanation about example

In [ ]:
# Example 2 - working
arr3[1:, 0:1, :2]

array([[[15., 16.]],

       [[98., 32.]]])

Explanation about example

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
arr3[1, 1, 2,1]

IndexError: too many indices for array: array is 3-dimensional, but 4 were indexed

Explanation about example (why it breaks and how to fix it)

Some closing comments about when to use this function.

In [ ]:
jovian.commit()

[jovian] Detected Colab notebook...
[jovian] jovian.commit() is no longer required on Google Colab. If you ran this notebook from Jovian, 
then just save this file in Colab using Ctrl+S/Cmd+S and it will be updated on Jovian. 
Also, you can also delete this cell, it's no longer necessary.


## Conclusion

Summarize what was covered in this notebook, and where to go next

## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* ...

In [ ]:
jovian.commit()

[jovian] Detected Colab notebook...
[jovian] jovian.commit() is no longer required on Google Colab. If you ran this notebook from Jovian, 
then just save this file in Colab using Ctrl+S/Cmd+S and it will be updated on Jovian. 
Also, you can also delete this cell, it's no longer necessary.
