In [1]:
import numpy as np

In [7]:
arr = np.array([[1,2,3,4,5,6,7,8,9]] , np.int64)

In [8]:
arr

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]], dtype=int64)

In [10]:
arr.shape

(1, 9)

In [12]:
arr.dtype    # search numpy types reference

dtype('int64')

In [14]:
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [15]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
zeros = np.zeros((2,5))

In [17]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
rng = np.arange(15)

In [19]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [20]:
lspace = np.linspace(1,5,10)

In [21]:
lspace

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [22]:
emp = np.empty((4,3))

In [23]:
emp

array([[6.93006856e-312, 2.86558075e-322, 0.00000000e+000],
       [0.00000000e+000, 1.69119330e-306, 1.16095484e-028],
       [2.31928612e-152, 1.14568603e+243, 3.52157235e-110],
       [6.32672800e+180, 4.74483502e+170, 4.59210323e-072]])

In [26]:
ide = np.identity(50)

In [27]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [29]:
arr3 = np.arange(99)

In [30]:
arr3.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [31]:
arr3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [32]:
x = [[1,2,3],[4,5,6],[7,8,9]]

In [33]:
ar = np.array(x)

In [35]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
ar.sum(axis=0)   # sums of col

array([12, 15, 18])

In [40]:
ar.sum(axis=1)  # sum of rows

array([ 6, 15, 24])

In [41]:
ar.sum()   # sum of all element

45

In [42]:
ar.ndim

2

In [43]:
 one = np.array([1,6,335,8,6])

In [46]:
one.argmax()   # give index of element of max value

2

In [47]:
one.argsort()

array([0, 1, 4, 3, 2], dtype=int64)

In [49]:
ar2 = np.array([[5,6,4],[8,2,6],[3,1,7]])

In [50]:
ar2

array([[5, 6, 4],
       [8, 2, 6],
       [3, 1, 7]])

In [52]:
ar+ar2

array([[ 6,  8,  7],
       [12,  7, 12],
       [10,  9, 16]])

In [53]:
ar*ar2

array([[ 5, 12, 12],
       [32, 10, 36],
       [21,  8, 63]])

In [55]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [56]:
np.where(ar>5)

(array([1, 2, 2, 2], dtype=int64), array([2, 0, 1, 2], dtype=int64))

In [57]:
np.count_nonzero(ar)

9